### ISSUE TITLE
Remove awssqs dependency

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-autoscaler-keda#235]
There was an attempt to remove [eventing-awssqs](https://github.com/knative-sandbox/eventing-awssqs) from the release train (and might eventually be deprecated) but since this repo depends on it the attempt failed. 

Any objections in deleting the code in the repo related to awssqs? 

@zroubalik @antoineco @odacremolbap @matzew

**Comment by dprotaso** [comment]
Can we get this sorted before the next release?

**Comment by dprotaso** [comment]
Otherwise we'll want to re-introduce sqs  again since it was removed from the release process - https://github.com/knative/release/pull/80

**Comment by dprotaso** [comment]
Just following up - the release is 3 weeks away - are we dropping awssqs from here?

**Comment by zroubalik** [comment]
Yeah, I will remove it. Though I am off till the end of the next week, so will do that then.

**Comment by dprotaso** [comment]
Bump

**Comment by zroubalik** [comment]
On it, sorry missed this.
