### ISSUE TITLE
Add support for 1-way TLS

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-autoscaler-keda#47]
KafkaSource supports 1-way TLS and the autoscaler should too. 

Current behavior: the autoscaler pod crashes

**Comment by zroubalik** [comment]
@lionelvillard could you please be more specific? Paste the error message or something?
This part of the code should do the job, or am I wrong?
https://github.com/knative-sandbox/eventing-autoscaler-keda/blob/9bc24c4d58d947594adcfebc297a0ce675f38caa/pkg/reconciler/kafka/kafka.go#L118-L144

**Comment by lionelvillard** [comment]
This has been fixed. IIRC the issue was in KEDA. Please reopen if you think something else needs to be done.
