### ISSUE TITLE
Figure out why kafka does not float properly.

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/eventing-autoscaler-keda#74]
As seen in #73 the kafka is improperly "ugpraded" to .19 instead of .20 like all the others.

@n3wscott any thoughts on this?

**Comment by lionelvillard** [comment]
`v0.19.1-0.20210128073630-1d9c884c16c6` points to the latest commit (1d9c884c16c67fbd3befc106fe8374ec383ed5df). I didn't figure out yet why the [peuso-version](https://golang.org/ref/mod#pseudo-versions) is v0.19.1.

**Comment by lionelvillard** [comment]
Here an idea: maybe there was no changes in the API after v0.19.1. Only few files are being imported, that might explain why.

**Comment by vaikas** [comment]
Thanks, yeah, when I floated the deps manually, I grabbed the very latest commit from the head and hence I was surprised why it tagged it in go.mod as 19. I just don't know if this is a problem or not, just seemed odd, so figured I'll jot it down.
